export const categories = [
  { value: "uncategorized", label: "Select a category", icon: "fas fa-question-circle" },
  { value: "physical-development", label: "Physical Development", icon: "fas fa-running" },
  { value: "cognitive-development", label: "Cognitive Development", icon: "fas fa-brain" },
  { value: "social-emotional-development", label: "Social & Emotional Development", icon: "fas fa-heart" },
  { value: "language-development", label: "Language Development", icon: "fas fa-comments" },
  { value: "motor-skills", label: "Motor Skills", icon: "fas fa-child" },
  { value: "sensory-development", label: "Sensory Development", icon: "fas fa-eye" },
  { value: "behavioral-development", label: "Behavioral Development", icon: "fas fa-smile" },
  { value: "early-intervention", label: "Early Intervention", icon: "fas fa-baby" },
  { value: "special-needs", label: "Special Needs", icon: "fas fa-hands-helping" },
  { value: "autism-spectrum", label: "Autism Spectrum", icon: "fas fa-puzzle-piece" },
  { value: "adhd", label: "ADHD", icon: "fas fa-bolt" },
  { value: "learning-disabilities", label: "Learning Disabilities", icon: "fas fa-book-reader" },
  { value: "emotional-regulation", label: "Emotional Regulation", icon: "fas fa-balance-scale" },
  { value: "attachment", label: "Attachment", icon: "fas fa-hand-holding-heart" },
  { value: "parenting-strategies", label: "Parenting Strategies", icon: "fas fa-lightbulb" },
  { value: "play-and-learning", label: "Play and Learning", icon: "fas fa-gamepad" },
  { value: "nutrition-and-health", label: "Nutrition and Health", icon: "fas fa-apple-alt" },
  { value: "sleep-and-routines", label: "Sleep and Routines", icon: "fas fa-bed" },
  { value: "speech-therapy", label: "Speech Therapy", icon: "fas fa-microphone" },
  { value: "occupational-therapy", label: "Occupational Therapy", icon: "fas fa-tools" },
  { value: "physical-therapy", label: "Physical Therapy", icon: "fas fa-dumbbell" },
  { value: "emotional-therapy", label: "Emotional Therapy", icon: "fas fa-heartbeat" },
  { value: "family-dynamics", label: "Family Dynamics", icon: "fas fa-users" },
  { value: "school-readiness", label: "School Readiness", icon: "fas fa-school" },
  { value: "peer-relations", label: "Peer Relations", icon: "fas fa-user-friends" },
  { value: "bullying", label: "Bullying", icon: "fas fa-angry" },
  { value: "screen-time-and-technology", label: "Screen Time and Technology", icon: "fas fa-tv" },
  { value: "parenting-self-care", label: "Parenting Self-Care", icon: "fas fa-spa" },
];

export default categories;
